package Entity;

public class Pension {
    private final int pensionId;
    private String type;


    public Pension(int pensionId, String type) {
        this.pensionId = pensionId;
        this.type = type;
    }

    // Constructor without pensionId, as it's auto-generated by the database
    // Use this constructor when creating a new Pension before saving to the database
    public Pension(String type) {
        this.pensionId = 0; // A placeholder, actual value will be set by the database
        this.type = type;
    }

    // Getter and Setter for type
    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    // Getter for pensionId, no setter as it's auto-generated
    public int getPensionId() {
        return pensionId;
    }
}
